server:
  port: 8087
  servlet:
    context-path: /online-queue/credentials

spring:
  application:
    name: OnlineQueueSecurity
  datasource:
    username: postgres
    password: Enter5510
    url: jdbc:postgresql://localhost:5432/OnlineQueue
    driver-class-name: org.postgresql.Driver
  cloud:
    openfeign:
      client:
        config:
          jwt-client:
            url: http://localhost:8084/
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full